# Generated by Django 4.1.6 on 2023-02-08 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='book')),
                ('title', models.CharField(max_length=400)),
                ('subtitle', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('version', models.FloatField(default=1)),
                ('size', models.FloatField(default=1)),
                ('os', models.FloatField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advantage', models.CharField(max_length=400)),
                ('downland', models.CharField(max_length=400)),
                ('url_name', models.CharField(max_length=200)),
                ('screen', models.ImageField(upload_to='images/')),
                ('likes', models.BigIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category')),
            ],
        ),
    ]
