# Generated by Django 4.1.6 on 2023-02-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='screen1',
            field=models.ImageField(default=1, upload_to='good/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='screen2',
            field=models.ImageField(default=1, upload_to='cool/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='downland',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='users',
            name='size',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='users',
            name='url_name',
            field=models.CharField(max_length=2000),
        ),
    ]
