# Generated by Django 4.1.6 on 2023-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_users_screen1_users_screen2_alter_users_downland_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='likes',
        ),
        migrations.AddField(
            model_name='users',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='project.category'),
        ),
    ]
