# Generated by Django 4.1.6 on 2023-02-19 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_remove_users_likes_users_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='downland',
            field=models.URLField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='users',
            name='url_name',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='users',
            name='version',
            field=models.CharField(max_length=300),
        ),
    ]
