# Generated by Django 4.1.6 on 2023-02-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='likes',
        ),
        migrations.AddField(
            model_name='users',
            name='likes',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
