# Generated by Django 3.2.7 on 2021-09-07 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_childern_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childern',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='apps.childern'),
        ),
    ]
